### ISSUE TITLE
Issues with displaying plotly graphs

### ISSUE THREAD

**Issue by yizhao3721** [deepnote/notebook#1]
Hi! 

I'm trying to graph a simple pie chart on Deepnote using plotly but my graphs are not displaying. The code compiles and runs successfully, and there is a green check mark on the code chunk. There is also a wide expanse of white space attached to the code chunk (presumably for the graph to go in), but the white space is empty and no graph is displayed.

I have attached the code chunk below. Thanks!

```
import plotly.graph_objects as go

X = ["a", "a", "b", "b", "b", "b", "c", "c", "d", "f", "f", "f", "f"]


fig = go.Figure()

fig.add_trace(go.Pie(values=X))

fig.show()
```

**Comment by robertlacok** [comment]
Thanks for reaching out! However, this is not the best public forum, we don't use this repo very much (it's ancient and due for clean up). Next time - please try community.deepnote.com! :) 

Regarding the plotly issue - thanks, I was able to replicate it. It's weird because sometimes it shows and sometimes it doesn't. We'll need to have a look at what's causing this - it used to work fine just last week, so we probably introduced some bugg. I found refreshing the page helps show the charts in the meantime.
